Repository Xeta-Team/Mobile-Shop-Website-Frontend, pull requests merged in 2025-09, with the labels that each got.

#11 Design admin dashboard side bar and make reusable components
  package-lock.json
  package.json
  src/App.jsx
  src/Components/Side Navigation Bars/AdminSideBarComponents/Btn.jsx
  src/Components/Side Navigation Bars/AdminSideBarComponents/DropDownBtn.jsx
  src/Components/Side Navigation Bars/AdminSideBarComponents/DropDownMenu.jsx
  src/Components/Side Navigation Bars/AdminSideNavBar.jsx
  src/Pages/Admin/AdminDashboard.jsx
  src/Pages/Admin/Dashboard Pages/MainDashboard.jsx
  src/Pages/Admin/Dashboard Pages/Products/AddProduct.jsx
  src/Pages/Admin/Dashboard Pages/Products/AllProducts.jsx
  src/Pages/Admin/Dashboard Pages/Users.jsx
  src/Pages/Home.jsx
  src/assest/logoTxt.png
  src/assest/shopLogo.png
Labels: development

#14 Design product Overview page
  src/Components/Image Models/FullscreenImage.jsx
  src/Components/Pages/Product Overview/ImageGallery.jsx
  src/Components/Pages/Product Overview/ProductDetails.jsx
  src/Pages/Home.jsx
  src/ProductOverView.jsx
Labels: development

#19 Dev sudira
  project_tree.txt
  src/App.jsx
  src/Components/Side Navigation Bars/AdminSideNavBar.jsx
  src/Components/Side Navigation Bars/SideBarComponents/Btn.jsx
  src/Components/Side Navigation Bars/SideBarComponents/DropDownBtn.jsx
  src/Components/Side Navigation Bars/SideBarComponents/DropDownMenu.jsx
  src/Components/Side Navigation Bars/UserSideNavBar.jsx
  src/Components/Toast/Toast.jsx
  src/Pages/Admin/Dashboard Pages/Products/AllProducts.jsx
  src/Pages/Admin/Dashboard Pages/Users.jsx
  src/Pages/User/Dashboard Pages/UserProfilePage.jsx
  src/Pages/User/UserDashboard.jsx
  src/Pages/UserReistration.jsx
Labels: development

#21 Stage #2
  package-lock.json
  package.json
  project_tree.txt
  src/Actions/CartActions.js
  src/App.css
  src/App.jsx
  src/Components/Buttons/NavigrationBarActionBtns.jsx
  src/Components/Buttons/SocialButton.jsx
  src/Components/Cards/HoverTranslateCard.jsx
  src/Components/Carousels/HomeCarousel.jsx
  src/Components/Collapse Model/CollapseMenu.jsx
  src/Components/EventListners/useAuthListener.jsx
  src/Components/Image Models/FullscreenImage.jsx
  src/Components/Input/InputField.jsx
  src/Components/Pages/Product Overview/ImageGallery.jsx
  src/Components/Pages/Product Overview/ProductDetails.jsx
  src/Components/Side Models/CartSideModel.jsx
  src/Components/Side Navigation Bars/AdminSideNavBar.jsx
  src/Components/Side Navigation Bars/SideBarComponents/Btn.jsx
  src/Components/Side Navigation Bars/SideBarComponents/DropDownBtn.jsx
  src/Components/Side Navigation Bars/SideBarComponents/DropDownMenu.jsx
  src/Components/Side Navigation Bars/UserSideNavBar.jsx
  src/Components/Table/ProductRow.jsx
  src/Components/Toast/Toast.jsx
  src/Pages/Admin/Dashboard Pages/Products/AddProduct.jsx
  src/Pages/Admin/Dashboard Pages/Products/AllProducts.jsx
  src/Pages/Admin/Dashboard Pages/Users.jsx
  src/Pages/Home.jsx
  src/Pages/Login.jsx
  src/Pages/User/Dashboard Pages/UserProfilePage.jsx
  src/Pages/User/UserDashboard.jsx
  src/Pages/UserReistration.jsx
  src/ProductOverView.jsx
Labels: enhancement, development

#24 Design landing pages and fix some bugs
  src/App.jsx
  src/Components/Buttons/NavigrationBarBtn.jsx
  src/Components/Footer.jsx
  src/Components/Side Navigation Bars/AdminSideNavBar.jsx
  src/Components/Side Navigation Bars/SideBarComponents/DropDownMenu.jsx
  src/Components/TopNavigationBar.jsx
  src/Pages/Admin/AdminDashboard.jsx
  src/Pages/Admin/Dashboard Pages/Products/AllProducts.jsx
  src/Pages/Admin/Dashboard Pages/Users.jsx
  src/Pages/Home.jsx
  src/Pages/ProductPages/Airpod.jsx
  src/Pages/ProductPages/Ipad.jsx
  src/Pages/ProductPages/Iphone.jsx
  src/Pages/ProductPages/Iwatch.jsx
  src/Pages/ProductPages/MacBook.jsx
  src/Pages/User/Dashboard Pages/UserProfilePage.jsx
  src/ProductOverView.jsx
  src/assest/large_2x.mp4
  src/assest/mac.jpg
  src/assest/mac.png
Labels: enhancement, development

#25 Stage #3
  package-lock.json
  package.json
  src/App.jsx
  src/Components/Buttons/NavigrationBarBtn.jsx
  src/Components/Footer.jsx
  src/Components/Side Navigation Bars/AdminSideNavBar.jsx
  src/Components/Side Navigation Bars/SideBarComponents/DropDownMenu.jsx
  src/Components/TopNavigationBar.jsx
  src/Pages/Admin/AdminDashboard.jsx
  src/Pages/Admin/Dashboard Pages/Products/AddProduct.jsx
  src/Pages/Admin/Dashboard Pages/Users.jsx
  src/Pages/Home.jsx
  src/Pages/Login.jsx
  src/Pages/ProductPages/Airpod.jsx
  src/Pages/ProductPages/Ipad.jsx
  src/Pages/ProductPages/Iphone.jsx
  src/Pages/ProductPages/Iwatch.jsx
  src/Pages/ProductPages/MacBook.jsx
  src/Pages/User/Dashboard Pages/UserProfilePage.jsx
  src/Pages/UserReistration.jsx
  src/ProductOverView.jsx
  src/assest/large_2x.mp4
  src/assest/mac.jpg
  src/assest/mac.png
  src/main.jsx
Labels: bug, enhancement, development, Updating

#26 Dev_lak
  package-lock.json
  src/Components/Cards/HoverTranslateCard.jsx
  src/Components/Carousels/HomeCarousel.jsx
  src/Components/Carousels/SliderCards.jsx
  src/Components/TopNavigationBar.jsx
  src/Components/popup/CartPopup.jsx
  src/Pages/Admin/Dashboard Pages/Products/AllProducts.jsx
  src/Pages/Home.jsx
  src/Pages/User/Dashboard Pages/UserProfilePage.jsx
Labels: enhancement, development

#27 Small changes and bug fixing
  package-lock.json
  package.json
  src/Actions/CartActions.js
  src/Actions/CartContext.jsx
  src/App.css
  src/App.jsx
  src/Components/Buttons/NavigrationBarActionBtns.jsx
  src/Components/Carousels/HomeCarousel.jsx
  src/Components/Carousels/SliderCards.jsx
  src/Components/Pages/Product Overview/ProductDetails.jsx
  src/Components/Side Models/CartSideModel.jsx
  src/Components/Side Models/Model Parts/Cart Model/Cart.jsx
  src/Components/Side Models/SearchSideModel.jsx
  src/Pages/Admin/AdminDashboard.jsx
  src/Pages/Admin/Dashboard Pages/Products/AllProducts.jsx
  src/Pages/Home.jsx
  src/Pages/User/Dashboard Pages/UserProfilePage.jsx
  src/Pages/User/UserDashboard.jsx
  src/Pages/UserReistration.jsx
  src/ProductOverView.jsx
  src/api/axiosConfig.js
  src/main.jsx
Labels: bug, development

#28 Implement orders showing section in user dashboard
  package-lock.json
  src/Pages/Order/Checkout.jsx
  src/Pages/User/Dashboard Pages/UserOrders.jsx
  src/Pages/User/UserDashboard.jsx
Labels: development
